### ISSUE TITLE
Layout of horizontal slider looks weird on iOS 12

### ISSUE THREAD

**Issue by benjaminfischer** [yonat/MultiSlider#11]
Xcode 10.0 beta 3 (10L201y)

…moving the slider crashes the App: `Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Multiplier is not finite!  That's illegal.  multiplier:inf'`

![simulator screen shot - iphone 8 - 2018-07-16 at 21 18 34](https://user-images.githubusercontent.com/944121/42778592-edac3962-893d-11e8-92c8-1f89bccf1257.png)

**Comment by yonat** [comment]
Oy vey, thanks for the report!
I hope to get to it before iOS 12 is released...

**Comment by Arthur-Guillaume** [comment]
Hi,

I have the same issue on iOS 12.

@yonat do you think you'll have time to fix it before the release of iOS 12 ?

**Comment by yonat** [comment]
It seems iOS 12 β has some problem with the `.rightMargin` constraint.
I pushed a workaround you can use, but I'll wait until the official iOS 12 release before bumping the pod version, because this problem may be fixed by then.

**Comment by Arthur-Guillaume** [comment]
Thanks for the feedback ans the temporary fix.

**Comment by Elshad** [comment]
My solution for this:

Changes in `MultiSlider.swift` file:
<img width="1068" alt="screen shot 2019-01-30 at 16 09 57" src="https://user-images.githubusercontent.com/2334731/51980635-14972200-24aa-11e9-997f-b1d35ad41ddf.png">

Result:
<img width="361" alt="screen shot 2019-01-30 at 16 13 22" src="https://user-images.githubusercontent.com/2334731/51980641-1c56c680-24aa-11e9-81f4-12e610b347b6.png">

**Comment by kavin06** [comment]
I am facing this error.Any one help ios 12.u fix this issue? please help me to solve this problem.

*** Assertion failure in -[NSLayoutConstraint _setMultiplier:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/Foundation/Foundation-1562/Foundation/Layout.subproj/NSLayoutConstraint.m:196
2019-03-11 12:39:32.198830+0530 DCON[3784:1325822] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Multiplier is not finite!  That's illegal.  multiplier:inf'
