### ISSUE TITLE
Slider not showing inside UIStackView

### ISSUE THREAD

**Issue by svastven** [yonat/MultiSlider#32]
**Description of the problem:**

I have made an instance of the slider and simply added it as and arranged subview to my stack view but the slider is shown in a very weird way. I am attaching an image where the blue line is supposed to be the slider. I have also tried to change its orientation to .horizontal but it did not help

``` swift
    private var slider: MultiSlider = MultiSlider()
    stack.addArrangedSubview(slider)
```

<img width="399" alt="Snímek obrazovky 2019-10-08 v 12 51 25" src="https://user-images.githubusercontent.com/42235915/66390229-883ee680-e9ca-11e9-80cc-5921364cdd8d.png">

**Comment by yonat** [comment]
Works for me...  
Please link to a project that reproduces the problem.

**Comment by xcentric-solutions** [comment]
I am seeing the same issue -- since the slider.orientation property is not exposed in IB, I set slider orientation in code using slider.orientation = horizontal to configure a horizontal slider. However, this means that all sliders are shown in vertical orientation in IB -- as shown in @svastven posted image. I am using the latest version of MultiSlider with Xcode Version 11.2.1 (11B53).

**Comment by yonat** [comment]
Ah, in IB! I added `isVertical` property that can be changed in IB, please update your pod to 10.0.1.

**Comment by xcentric-solutions** [comment]
Works perfectly!

Thank you yonat 🙏🏽
