### ISSUE TITLE
Avoid extensions and sugar libs.

### ISSUE THREAD

**Issue by NikKovIos** [yonat/MultiSlider#41]
1) Avoid extensions. I have a very big project and if every framework would add as many extensions as this, it would be a project-blow. I fixed it by moving all code of MultiSlider to one file and marking the extensions `fileprivate`.
2) This is not a big lib. However it has 2 dependencies https://github.com/yonat/AvailableHapticFeedback and https://github.com/yonat/SweeterSwift. For example Alamofire - large framework has zero dependencies. This is not a good style to multiply them just for a few functions.

**Comment by yonat** [comment]
1. The extensions are `internal` so do not pollute the global namespace.
  (`internal` is like `fileprivate` for modules -- see [The Swift Programming Language](https://docs.swift.org/swift-book/LanguageGuide/AccessControl.html).)

2. There is always a tradeoff between having dependencies versus having code duplication across modules. Since I use this same code in several different modules and projects, I chose to avoid the duplication in this case.
